builds:
- id: foo
  dir: .  # default is .
  main: .
#   env:
#   - GOPRIVATE=git.internal.example.com,source.developers.google.com
  flags:
  - -tags
  - netgo
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.gitVersion={{.Env.GIT_VERSION}}
  - -X main.gitSomething={{.Env.GIT_SOMETHING}}
