builds:
- id: foo
  dir: .  # default is .
  main: .
#   env:
#   - GOPRIVATE=git.internal.example.com,source.developers.google.com
  flags:
  - -tags
  - netgo
  ldflags:
#   - -s -w
#   - -extldflags "-static"
#   - -X main.version={{.Env.VERSION}}
