name: SLSA Release

on: workflow_dispatch

permissions: read-all

env:
  BUILDER_GO_VERSION: 1.18

jobs:
  build:
    name: SLSA Golang builder
    runs-on: ubuntu-latest
    steps:
      - uses: laurentsimon/slsa-on-github/builder-golang@feat/actionfetch
        with:
          go-version: ${{ env.BUILDER_GO_VERSION }}
  
  test:
    name: My test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: SLSA_BINARY
      - run: |
          ls -a SLSA_BINARY
          ./SLSA_BINARY
