name: SLSA Release

on: 
  workflow_dispatch:
  push:
    tags:
      - "*" 

permissions: read-all

jobs:
  build:
    name: SLSA Golang builder
    permissions:
      id-token: write
      contents: read
    uses: slsa-framework/slsa-github-generator-go/.github/workflows/builder.yml@main
    with:
      go-version: 1.17

  upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          pwd
          ls
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }}
      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ needs.build.outputs.go-binary-name }}
            ${{ needs.build.outputs.go-binary-name }}.intoto.sig

#   test:
#     name: My test
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - uses: 'actions/download-artifact@v2'
#         with:
#           name: SLSA_BINARY
#       - run: |
#           ls -l SLSA_BINARY
#           chmod a+x SLSA_BINARY
#           ./SLSA_BINARY
