name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  args:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO generate arguments"
      
  build:
    uses: laurentsimon/slsa-on-github/.github/workflows/test-reusable-go.yml@feat/reusable
    with:
      go-version: 1.17

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          echo ./${{ needs.job1.outputs.go-binary-name }}
