name: Go push main

on: 
  push:
    branches: [ main ]

permissions: read-all

env:
  TARGET_REPOSITORY: laurentsimon/slsa-on-github-test # TODO: update with slsa go
  ISSUE_TITLE: "E2E failure: Go push main"

jobs:
  #TODO: support multiple config files.
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello
          exit -1

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (needs.build.result == 'failure')
    env:
      GH_TOKEN: ${{ secrets.E2E_TOKEN }}
    steps:
      - run: |
          #TODO: create issue on the repo about the failure.
          
          cat << EOF > BODY
          Repo: $GITHUB_REPOSITORY@$GITHUB_REF_NAME
          Workflow name: Go push main
          Workflow file: [$GITHUB_REPOSITORY/.github.com/workflows/e2e.yml](https://github.com/$GITHUB_REPOSITORY/.github.com/workflows/e2e.yml)
          Trigger: push
          Branch: main
          Private repo : false
          EOF
          
          gh issue create -t "$ISSUE_TITLE" -F ./BODY -R "$TARGET_REPOSITORY"  
