on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: asraa/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@malicious
    with:
      go-version: 1.18
      config-file: .config.yml
      compile-builder: true
