on:
  workflow_dispatch:

permissions: read-all

jobs:
  build-container-based:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For reading workflow info.
    uses: asraa/slsa-github-generator/.github/workflows/builder_container-based_slsa3.yml@main
    with:
      builder-image: "bash"
      builder-digest: "sha256:9e2ba52487d945504d250de186cb4fe2e3ba023ed2921dd6ac8b97ed43e76af9"
      config-path: "config.toml"
      compile-builder: true
