name: Ko Caller

on: 
  workflow_dispatch:
  push:
    tags:
      - "*" 

permissions: read-all

jobs:
  build:
    name: KO SLSA builder
    permissions:
      id-token: write
      contents: read
      packages: write
    #uses: slsa-framework/slsa-github-generator-go/.github/workflows/builder.yml@main
    uses: laurentsimon/slsa-on-github-test/.github/workflows/ko-builder.yml@main
    with:
      args: -B --platform=linux/amd64,linux/arm64,linux/386,linux/arm --tags=tag5,tag6 laurentsimon/helloworld
      username: laurentsimon
    secrets:
      password: ${{ secrets.DOCKER_TOKEN }}

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print
        run: |
          echo "${{ needs.build.outputs.image }}"
