name: Ko Release

on: 
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        description: Registry
        options: 
        - docker.io
        - ghcr.io
  push:
    tags:
      - "*" 

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PLATFORMS: linux/amd64,linux/arm64,linux/386,linux/arm
      TAGS: tag1,tag2,tag3
      # Note: "." works to in this simple case
      PROJECT: laurentsimon/helloworld
      GIHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      USERNAME: laurentsimon
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
       # Note: downlaoading and pinning the download seems better
       # than adding this dependency. Need to look how the install works
       # remko/dsadmin/blob/7a6939179bc56b1be28cada040f2b4a148e3e14a/.github/workflows/publish-release.yml
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.4
    
      - name: docker
        if: ${{ github.event.inputs.registry == "docker.io"}}
        run: |
          #TODO: set -e
          ko login docker.io -u laurentsimon -p "$DOCKER_TOKEN"
          KO_DOCKER_REPO="docker.io/laurentsimon" ko publish -B --platform "$PLATFORMS" --tags "$TAGS" "$PROJECT"
      
      - name: github
        if: ${{ github.event.inputs.registry == "ghcr.io"}}
        run: |
          #TODO: set -e
          ko login ghcr.io -u laurentsimon -p "$GIHUB_TOKEN"
          ko publish -B --platform "$PLATFORMS" --tags "$TAGS" "$PROJECT"
