name: Original SLSA

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DIGEST: NULL
  BUILDER_GO_VERSION: 1.17

jobs:
  # verify-scorecard:
  #   name: verify scorecard
  #   runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: laurentsimon/slsa-on-github/builder-golang@feat/actionfetch
        with:
          go-version: ${{ env.BUILDER_GO_VERSION }}
  
  provenance:
    permissions:
      id-token: write
      packages: write
      contents: read

    name: provenance
    runs-on: ubuntu-latest
    # Requires build to complete
    needs: build
    steps:
      # TODO package all of this into an action
      - uses: actions/checkout@v2.4.0
        with:
          repository: 'asraa/slsa-on-github'
      - uses: actions/setup-go@v2
      - name: build provenance generator
        run: go build -o prov ./cmd/main.go

      # Download build from previous job
      - uses: 'actions/download-artifact@v2'
        with:
          name: SLSA_BINARY

      - name: Generate provenance for build in previous job
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export DIGEST=$(sha256sum SLSA_BINARY | awk '{print $1}')
          ./prov -repository ${{ github.repository }} -digest $DIGEST > att.provenance
          ls
      
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # sign binary and provenance and upload to Container registry
      - uses: sigstore/cosign-installer@main
      - name: Upload binary as blob and sign with provenance
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign upload blob -f SLSA_BINARY ghcr.io/laurentsimon/slsa-on-github-test
          cosign sign ghcr.io/laurentsimon/slsa-on-github-test
          cosign attest --predicate att.provenance ghcr.io/laurentsimon/slsa-on-github-test
