name: Go SLSA Release

on: 
  workflow_dispatch:
  push:
    tags:
      - "*" 

permissions: read-all

jobs:
  build:
    name: SLSA Golang builder
    permissions:
      id-token: write # For signing
      contents: write # For asset uploads. Always needed, even when not setting `upload-assets: false` :/
    #uses: slsa-framework/slsa-github-generator-go/.github/workflows/slsa3_builder.yml@main
    uses: asraa/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@configure-rekor-url
    with:
      go-version: 1.17
      upload-assets: false
      config-file: ./.github/workflows/go-configs/config1.yml
      compile-builder: true
      rekor-url: "https://rekor.sigstage.dev"

  upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          pwd
          ls
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }}
      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ needs.build.outputs.go-binary-name }}
            ${{ needs.build.outputs.go-binary-name }}.intoto.sig
