name: SLSA go building workflow
on:
  workflow_dispatch:

permissions: read-all

# env:
#   ENV_TEST: "some tests env variable"
      
jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      ldflags: ${{ steps.ldflags.outputs.value }}
    steps:
      - id: ldflags
        run: |
          echo "::set-output name=value::-X github.com/ossf/scorecard/v4/pkg.gitVersion=v3.2.1-208-g8d67482"

  build:
    env:
      VERSION_LDFLAGS: ${{needs.args.outputs.ldflags}}
    permissions:
      id-token: write
      #packages: write
      contents: read
    runs-on: ubuntu-latest
    needs: args
    steps:
      - uses: laurentsimon/slsa-on-github/.github/workflows/slsa-builder-go.yml@feat/args

  upload:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }}
