name: SLSA go building workflow
on:
  workflow_dispatch:

permissions: read-all

# env:
#   ENV_TEST: "some tests env variable"
      
jobs:
  args:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO generate arguments"
      
  build:
    permissions:
      id-token: write
      #packages: write
      contents: read
    needs: args
    uses: laurentsimon/slsa-on-github/.github/workflows/slsa-builder-go.yml@feat/args
    with:
      go-version: 1.17
      goos: linux
      goarch: amd64
      envs: ENV_TEST="some tests env variable", ENV_TEST2="another one"
      #ldflags: 

  upload:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }}
