name: SLSA go building workflow
on:
  workflow_dispatch:

jobs:
  args:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO generate arguments"
      
  build:
    needs: args
    uses: laurentsimon/slsa-on-github/.github/workflows/slsa-builder-go.yml@feat/reusable
    with:
      go-version: 1.17

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      - run: |
          echo name is ${{ needs.build.outputs.go-binary-name }}
          chmod a+x ./${{ needs.build.outputs.go-binary-name }}
          ./${{ needs.build.outputs.go-binary-name }}
